### ISSUE TITLE
Employee tracker

### ISSUE THREAD

**Issue by jonghoBae0218** [jonghoBae0218/employee_tracker#1]
- [x] WHEN I start the application, I am presented with the following options: view all departments, view all roles, view all employees, add a department, add a role, add an employee, and update an employee role
- [x] WHEN I choose to view all departments, I am presented with a formatted table showing department names and department ids
- [x] WHEN I choose to view all roles, I am presented with the job title, role id, the department that role belongs to, and the salary for that role
- [x] WHEN I choose to view all employees, I am presented with a formatted table showing employee data, including employee ids, first names, last names, job titles, departments, salaries, and managers that the employees report to
- [x] WHEN I choose to add a department, I am prompted to enter the name of the department and that department is added to the database
- [x] WHEN I choose to add a role, I am prompted to enter the name, salary, and department for the role and that role is added to the database
- [x] WHEN I choose to add an employee, I am prompted to enter the employee’s first name, last name, role, and manager, and that employee is added to the database
- [x] WHEN I choose to update an employee role, I am prompted to select an employee to update and their new role and this information is updated in the database

**Comment by jonghoBae0218** [comment]
1,2 commit to setup db

**Comment by jonghoBae0218** [comment]
3 to add prompt. resolved issue 1

**Comment by jonghoBae0218** [comment]
4 to add view departments. resolved issue 2

**Comment by jonghoBae0218** [comment]
5 to add view roles. resolved issue 3

**Comment by jonghoBae0218** [comment]
6th commit to add view employees. resolved issue 4

**Comment by jonghoBae0218** [comment]
7th commit to add addDepartment. resolved issue 5

**Comment by jonghoBae0218** [comment]
8th commit to add addRole. resolved issue 6

**Comment by jonghoBae0218** [comment]
9th commit to add addEmployee. resolved issue 7

**Comment by jonghoBae0218** [comment]
10th commit to add updateEmployeeRole. resolved issue 8

**Comment by jonghoBae0218** [comment]
11th commit added updateEmployeeManager function.

**Comment by jonghoBae0218** [comment]
12,13,14 commit to add comment, readme, refine files.
